<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="hyphen_exc.dic" />
        <EmbeddedResource Include="hyph_en_US.dic" />
        <None Update="Multimodal.docx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.Win.BonusSkins" Version="24.2.*" />
        <PackageReference Include="DevExpress.Document.Processor" Version="24.2.*" />
        <PackageReference Include="DevExpress.Win.RichEdit" Version="24.2.*" />
        <PackageReference Include="DevExpress.Win.SpellChecker" Version="24.2.*" />
    </ItemGroup>
</Project>